---
- hosts: localhost
  tasks:
    - name: Encode all non-yml files in this directory with Caesar cipher (shift by one)
      shell: |
        for file in `ls | grep -v '.yml'`
          do printf "`tr [a-zA-Z] [b-zaB-ZA] < $file`\n" > $file
        done
